-- create
CREATE TABLE EMPLOYEE (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL
);

-- insert
INSERT INTO EMPLOYEE VALUES (0001, 'Елена', 35);
INSERT INTO EMPLOYEE VALUES (0002, 'Матей', 18);
INSERT INTO EMPLOYEE VALUES (0003, 'Илья', 10);
INSERT INTO EMPLOYEE VALUES (0004, 'Мия', 18);
INSERT INTO EMPLOYEE VALUES (0005, 'Егор', 14);
INSERT INTO EMPLOYEE VALUES (0006, 'Саша', 40);
INSERT INTO EMPLOYEE VALUES (0007, 'Федор', 15);
INSERT INTO EMPLOYEE VALUES (0008, 'Дмитрий', 17);
INSERT INTO EMPLOYEE VALUES (0009, 'Иван', 24);
INSERT INTO EMPLOYEE VALUES (0010, 'Корней', 60);

-- fetch 
SELECT * FROM EMPLOYEE WHERE age >= 18;